### PR TITLE
clean up the C# code

### PR DESCRIPTION
**Pull request by acesnik**
I think this is working... I'm not sure why the GUI is building into the main directory instead of into the bin. I got the docker instance to download, but I'm not sure it ran just yet.

### CODE REVIEW

**Comment by acesnik** [comment]
@bintiibrahim I moved your genome resources into the GUI project to be able to build into the bin instead of the main directory. I also deleted the bulk of my old C# code.

It seems to run the Powershell commands properly, but it's not running any of the snakemake scripts.

**Comment by acesnik** [comment]
Let's also make a Docker Hub repository for the master branch here instead of in your fork. Hopefully, it works.

**Comment by bintiibrahim** [comment]
> @bintiibrahim I moved your genome resources into the GUI project to be able to build into the bin instead of the main directory. I also deleted the bulk of my old C# code.
> 
> It seems to run the Powershell commands properly, but it's not running any of the snakemake scripts.

I don't think you merged in my edits to the Dockerfile from `rinaibrhm/species`!

**Comment by acesnik** [comment]
Okay, could you make a small pull request into `bigcleanup` with just the Dockerfile?

**Comment by acesnik** [comment]
I think everything is working now, except for the old Docker container. I'm going to merge.

**Pull request merged**
