### PR TITLE
latest spritz gui and snakemake

### PR DESCRIPTION
**Pull request by bintiibrahim**
you can probably ignore the GtfSharp and TransferUniProtModification conflicts with mine, i didn't change any of those. :)

### CODE REVIEW

**Comment by bintiibrahim** [comment]
@acesnik this PR actually contains the latest snakemake code AND the GUI edits. i think i'll close this PR https://github.com/acesnik/SpritzSnake/pull/17 because it doesn't match with the edits in this PR.

**Comment by acesnik** [comment]
Hmm, sounds good. The conflicts here are confusing in GitHub, too. I would like the two repositories to match up before we make more changes. Maybe I'll just add the current snakemake code without deleting anything, and then we can layer in these changes.

**Comment by acesnik** [comment]
`download_protein_xml.py` needs to accomodate multiple species. Right now, the UniProt proteome is still hardcoded.

**Comment by acesnik** [comment]
Do we need to consider using different SnpEff codon tables for different organisms?

**Comment by bintiibrahim** [comment]
> `download_protein_xml.py` needs to accomodate multiple species. Right now, the UniProt proteome is still hardcoded.

I've actually made this accomodation. In the `rule download_protein_xml` you'll see that I'm calling `get_proteome.py` and `download_xml.py`

**Comment by acesnik** [comment]
Tried to address all the conflicts here https://github.com/smith-chem-wisc/Spritz/pull/162. Going to close this one.

**Pull request closed without merging**
